#:schema node_modules/wrangler/config-schema.json
name = "lundry-id"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

[vars]
# Add environment variables here
